//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wish2DishWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commission
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<long> FromCustomer { get; set; }
        public Nullable<long> ToCustomer { get; set; }
        public Nullable<int> ProductBatchId { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> SalesBillId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ProductBatch ProductBatch { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
    }
}
