//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wish2DishWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductBatch()
        {
            this.Commissions = new HashSet<Commission>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> PP { get; set; }
        public Nullable<decimal> Exp { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> Prof { get; set; }
        public Nullable<decimal> Stock { get; set; }
    
        public virtual Batch Batch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commission> Commissions { get; set; }
        public virtual Product Product { get; set; }
    }
}
